image: node:10

stages:
  - build
  - test
  - deploy

install:
  stage: build
  cache:
    paths:
      - .npm-cache
  before_script:
    - npm config set cache .npm-cache
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

lint+test:
  dependencies:
    - install
  script:
    - npm run lint
    - npm run test -- --color --coverage --reporters=default --reporters=jest-junit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      junit: junit.xml

pages:
  stage: deploy
  dependencies:
    - install
  script:
    - npm run doc
    - mv docs/ public/
  artifacts:
    paths:
      - public
  only:
    - master
