language: node_js
node_js:
- node
- lts/*
- lts/carbon
cache:
  directories:
  - "$HOME/.npm"
install: npm ci
jobs:
  include:
  - stage: release
    node_js: lts/*
    if: tag IS present AND repo = 'Socialbakers/BakeryJS'
    script: skip
    deploy:
      provider: npm
      skip_cleanup: true
      email:
        secure: rwB8GZihhZtAj2dfT4euRM8VdZk/noiqiEGEmHDy3+gYwc8uIZagQ1Gx8I3AiUDJAneoQvF61wPEAS7TEqHg62sqVHSyHn0ksIuT/geFsQQtU+JtH15RSSj9H2qq4v2lvZ/Tw1DWw/SWQV+FwNsIdMaljE22nXCdqQJeojI0WdO61AGIbvd6GOHigcb4WNI/g0mWK34VB4+BR6y+IyLcoPKaGo8/ETL2lcQgWx6HGupnt8Xct01sBXDfbM+SLG40jWN2DsxghwypwwCzL4yJzmuRdybw/Em3oz08O6Ofhm6vHbp5cUBnKCPzhPRj4k11/Ln2GVK4GE5AcVVMnvEErECxHFM8bKB84qLM0I9vnFwVGjXgTdu2/tVsSwpPFgRovNv3+4MA3EECXyy9LPC43I5GMFvjqEsYojmhQ7m9OB3b9qpLaUN6c+TCG7z8Tm1+yn+xqQwxJ4IOnenlC4CwTWLZVgrx0pbas+caK8vqzohQIz7ATKHl44BNhhoVHxzBxKub1kkyU7JYUPrsZDahDxxEvj3cB2xQXw9DSCiP4aQfx/9FrFK4ClmxHhL/+3DZf7LTIhcWKTjZ1d1RidJhU0GWzFvxwUkk2it8LJGYTC8B4thHBpGreLypBpN7E5rqBhIstqTMKG8EBXIRvidnSTDtwTiE3kC+8cyZmRv2DE0=
      api_key:
        secure: JcvfRvMQmgV8vlJlF9gRWkXz0ChOzmUqa1h2cX8LmVz/O+6BEVYjkDvZ4sOGfwCgdV2UX5+FB1tViWL4uCTYcS2qS220neS1Q6ttWay68f4dMhGOm13ZM8+ZJV5uQYgzGQhsRazNgmfzyqLiKVdOD7vBBfrB0SPs6CEWx8IiYn9K+pPlfIAr5g2kLKUnntOqdqTWUwhXehC23HrjsUrFXl3OMg90QHdb3d9u7f/LYGa7eYZj//VlcRtLD/9DOuOaqfFZ6qi61PWBrfuv+fWPSJf6irDE0CWtnXQmRf92PF70odGELXW1uS/VQM+Q4mc8cryEwTH8XGwXxVh0qKV+zphYmdd2AWXwcDvMKgvXy9iAdkYhg551UI4omRLGE2RHjFDcoSa9LKpxkxi7Ew4InxNZp1gvcWU4HBtSZu7ZY41pL2QwUrmQCEYBLy4pWhgXBVvXlQbJL0vTArhCC1gHnTfcy6JJf7qD2gG23b+EAeHTHcqV2HHEu4hZPtFDHDB2iMFqabRD6A463NdfoUHhSBcKD2MyY/skh2t7SVpTUL2IzDWGVpo4qI/2t9rvDCDQyFU4jryjOr1hBr4S8Cnh4LOaRXAGrroI43CfPzfgkNucHgF0Yo27eW8DJ/wMeCQvrGTiiMirr/Xb0Bb3abCBeK5u1Ifmas91PT8g12Swmlk=
        tags: true
        repo: Socialbakers/BakeryJS
notifications:
  slack:
    secure: bsPosC5EHo21GN5GISUZgPsy1yMRNbzTPlFKwTGtDAouT5NShJzwEsr8LeHwM8HcXnw4NTmZH+IId7HL1sTMJiv11/HcDt9FpQjxILIjOq6J6XsmaGbHIiA1u744+3OvChWuFxWUky3m/L8rVk55fM7ZNmKh2lr+6iufbtGJeCw137S0U9WzlOY3Ckp4Nct4EELCiYJBYNL4e2M0zq+vvpM67RLgbu3No4v1ym2Tx4Jm4oCKIpAqCYCWAnmfygxAaP0rxQDfGS62pgIELmqnovyUDikiL8xqucALSYxds5OedUJt9JChafe/++aygdv/NpFP6/TlOy07Wuw7O/tqdw0oLPFcC1MAydeKjvpg0HT4rL1kKCaxOz3iz7lkPYpv0njf5GpoaAGgwVHPPhKWbrurIhnlWdldI24nf+v9RdXBa1Vw/TzHukVudrUa2HP/AW4628bsUSnj8PPC0iPP193FtbY2+e6SHJ1VfgnuQzCiE0T+SAIXlnUXHlR9+EX6nAsRsE9sUtWMckpCrp28aR7bBD6gGVWyMGsCcPSzOVbYTxWkY6Us2xAKcU3qB0p3GQvemyh9TS2qYWW21ecOSKbhxcy1Gw/kZzb0+cGM5VaXO3uX17Xb9iw8N15JSU5P2SxP2pAoUJZernP3kFlFvWDHX8A0LHzceWRmA3KYCg8=
