/**
 * V8 CPU Profile Parser
 *
 * Parses .cpuprofile JSON files generated by Node.js --cpu-prof flag
 */

import * as fs from 'fs'
import { CpuProfile, CpuProfileNode, ProfileMetadata } from '../types'

/** Parsed profile with extracted metadata */
export interface ParsedProfile {
	/** The raw CPU profile data */
	profile: CpuProfile
	/** Extracted metadata */
	metadata: ProfileMetadata
	/** Map of node ID to node for quick lookup */
	nodeMap: Map<number, CpuProfileNode>
	/** Sample interval in microseconds */
	sampleIntervalUs: number
	/** Total profile time in microseconds */
	totalTimeUs: number
}

/**
 * Parse a CPU profile from a file
 * @param filePath Path to the .cpuprofile file
 * @returns Parsed profile data
 */
export function parseProfileFile(filePath: string): ParsedProfile {
	const content = fs.readFileSync(filePath, 'utf8')
	return parseProfileJson(content, filePath)
}

/**
 * Parse a CPU profile from JSON string
 * @param json JSON string of the CPU profile
 * @param filename Optional filename for metadata
 * @returns Parsed profile data
 */
export function parseProfileJson(json: string, filename: string = 'unknown'): ParsedProfile {
	const profile = JSON.parse(json) as CpuProfile

	// Build node map for quick lookup
	const nodeMap = new Map<number, CpuProfileNode>()
	for (const node of profile.nodes) {
		nodeMap.set(node.id, node)
	}

	// Calculate timing information
	const totalTimeUs = profile.endTime - profile.startTime
	const sampleCount = profile.samples?.length ?? 0

	// Calculate sample interval from time deltas or estimate from sample count
	let sampleIntervalUs: number
	if (profile.timeDeltas && profile.timeDeltas.length > 0) {
		const totalDeltaTime = profile.timeDeltas.reduce((sum, d) => sum + d, 0)
		sampleIntervalUs = totalDeltaTime / profile.timeDeltas.length
	} else if (sampleCount > 0) {
		sampleIntervalUs = totalTimeUs / sampleCount
	} else {
		// Default to 1ms (1000Hz sampling)
		sampleIntervalUs = 1000
	}

	// Calculate sample rate in Hz
	const sampleRateHz = sampleIntervalUs > 0 ? Math.round(1000000 / sampleIntervalUs) : 1000

	const metadata: ProfileMetadata = {
		filename: filename.split('/').pop() || filename,
		durationMs: totalTimeUs / 1000,
		sampleCount,
		sampleRateHz
	}

	return {
		profile,
		metadata,
		nodeMap,
		sampleIntervalUs,
		totalTimeUs
	}
}

/**
 * Get a node by ID from the parsed profile
 */
export function getNode(parsed: ParsedProfile, nodeId: number): CpuProfileNode | undefined {
	return parsed.nodeMap.get(nodeId)
}

/**
 * Get the root node of the profile (usually the first node)
 */
export function getRootNode(parsed: ParsedProfile): CpuProfileNode | undefined {
	// The root node is typically id=1 in V8 profiles
	return parsed.nodeMap.get(1) || parsed.profile.nodes[0]
}

/**
 * Calculate self time for a node based on hit count and sample interval
 * @param node The profile node
 * @param sampleIntervalUs Sample interval in microseconds
 * @returns Self time in milliseconds
 */
export function calculateSelfTimeMs(node: CpuProfileNode, sampleIntervalUs: number): number {
	return (node.hitCount * sampleIntervalUs) / 1000
}

/**
 * Check if a node represents native code or V8 internals
 */
export function isNativeOrInternal(node: CpuProfileNode): boolean {
	const { url, functionName } = node.callFrame

	// Empty URL usually indicates native code
	if (!url || url === '') {
		return true
	}

	// V8 native code markers
	if (url.startsWith('native ') || url.includes('v8/')) {
		return true
	}

	// Node.js internal modules
	if (url.startsWith('node:') || url.includes('internal/')) {
		return true
	}

	// Common patterns for garbage collection, compilation, etc.
	const internalPatterns = ['(garbage collector)', '(idle)', '(program)', '(root)']

	return internalPatterns.includes(functionName)
}

/**
 * Extract a clean file path from a URL
 */
export function extractFilePath(url: string): string {
	if (!url) {
		return '<native>'
	}

	// Remove file:// prefix if present
	const path = url.replace(/^file:\/\//, '')

	// For relative paths in the project, extract just the filename
	const match = path.match(/([^/]+\.(ts|js))$/)
	if (match) {
		return match[1] ?? path
	}

	return path
}

/**
 * Check if a URL belongs to BakeryJS source code
 */
export function isBakeryJsCode(url: string): boolean {
	if (!url) return false

	// Match source files in src/ or benchmarks/
	return url.includes('/src/') || url.includes('/benchmarks/')
}
